ssh_keys:
  personal:
    file_name:       id_ed25519
    op_shorthand:    me
    op_name_public:  SSH - Personal Main Public
    op_name_private: SSH - Personal Main Private

domain: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37373464646236326634356538343266636632346531323764663734303561376333393262666565
          3232343338373437636532643434363639656531356639640a376561376536666563633734366635
          63643835383034623436633935653666333331663530373032323466356661336431636464616563
          6666313432386365330a333531333038363730653963356265336565343039366566626136343130
          66303937313565636138383536623635336564616630376633333639393464633566
email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39363637343062333364663538363736643938393239633161316164353532636537623731343038
          3932633430646162323263343737343263613234343737320a623135626534356237333739663966
          37373130396335333535316263306264326462653531643135383831333066613430353362613361
          3663643039643037310a373633366465636334386630623764613532383831653430306161613239
          32303833363937653031313039376164343834633330303435343636373962356163
secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31383464643831663664353639346231396361666361373461623631393566663331626132343231
          3663386366363434666430366630326137656630323438300a316363313331623832653763373437
          38623266316636343536386533343365303337326261373738643536313738643965373536383339
          3665613036336633340a633735333337306563353630356164326238376232356139313832663961
          31313732653830633734623135613135353765356665333830333239393264333661633638313661
          6264363936653766616365316236653139353461333061333165
password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333935363233366462326462396435396164633730366464646239376630333062363631303833
          3134633835323637366334373564353637636263363866370a646430326431363339316639316364
          34313661656131313432343062343336616532303336343032303939613265626665643034653836
          6462386337633032380a356333653539636162366535613563313130383333623764363430666137
          3934
